name: Remote readmeSync
on:
  schedule:
    - cron: "0 5,17 * * *"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout private build
        uses: actions/checkout@v4

      - name: checkout public profile
        uses: actions/checkout@v4
        with:
          repository: aadnanmt/aadnanmt
          token: ${{ secrets.GH_TOKEN }}
          path: public-repo

      - uses: oven-sh/setup-bun@v1

      - name: install & generate
        run: |
          bun i
          bun run scripts/index.ts ./public-repo/README.md ./stats.json
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: format code
        run: bun run format:readme

      - name: push to public repo
        working-directory: ./public-repo
        run: |
          git config --local user.email "contact@aadnanmt.web.id"
          git config --local user.name "Adnan Slamet Wibowo"
          git add README.md
          git commit -m "docs: sync automated README.md [skip ci]" || exit 0
          git push origin main

      - name: push stats to this repo
        run: |
          git config --local user.email "contact@aadnanmt.web.id"
          git config --local user.name "Adnan Slamet Wibowo"
          git add stats.jso
          git commit -m "data: update stats.json for portfolio [skip ci]" || exit 0
          git push origin main
