name: Remote README Sync
on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout private build
        uses: actions/checkout@v4

      - name: checkout public profile
        uses: actions/checkout@v4
        with:
          repository: aadnanmt/aadnanmt
          token: ${{ secrets.GITHUB_TOKEN }}
          path: public-repo

      - uses: oven-sh/setup-bun@v1

      - name: install & generate
        run: |
          bun install
          bun run scripts/index.ts ./public-repo/README.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: push to public repo
        working-directory: ./public-repo
        run: |
          git config --local user.email "contact@aadnanmt.web.id"
          git config --local user.name "aadnanmt"
          git add README.md
          git commit -m "docs: sync automated stats [skip ci]" || exit 0
          git push origin main